spring:
  security:
    user:
      name: username
      password: password
  datasource:
    url: jdbc:mysql://localhost:3306/miniautorizador
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  mongodb:
    uri: mongodb://user:password@localhost:27017/miniautorizador

server:
  port: 8080